namespace Kontent.Ai.Management.Models.Workflow;

/// <summary>
/// Payload for creating or replacing a workflow.
/// </summary>
public sealed record WorkflowUpsertModel
{
    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Scopes this workflow applies to. The array is required (cannot be omitted) but may be empty.
    /// </summary>
    [JsonPropertyName("scopes")]
    public required IEnumerable<WorkflowScopeUpsertModel> Scopes { get; init; }

    /// <summary>
    /// Custom workflow steps.
    /// </summary>
    [JsonPropertyName("steps")]
    public required IEnumerable<WorkflowStepUpsertModel> Steps { get; init; }

    /// <summary>
    /// Published system step configuration.
    /// </summary>
    [JsonPropertyName("published_step")]
    public required WorkflowPublishedStepUpsertModel PublishedStep { get; init; }

    /// <summary>
    /// Archived system step configuration.
    /// </summary>
    [JsonPropertyName("archived_step")]
    public required WorkflowArchivedStepUpsertModel ArchivedStep { get; init; }
}
