namespace Kontent.Ai.Management.Models.Workflow;

/// <summary>
/// Payload for a custom workflow step inside a workflow upsert.
/// </summary>
public sealed record WorkflowStepUpsertModel
{
    /// <summary>
    /// Step ID. Only set when editing an existing step within a workflow; omit when defining a new step.
    /// </summary>
    [JsonPropertyName("id")]
    public Guid? Id { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// UI color shown for this step.
    /// </summary>
    [JsonPropertyName("color")]
    public required WorkflowStepColor Color { get; init; }

    /// <summary>
    /// Workflow steps that this step can transition to.
    /// </summary>
    [JsonPropertyName("transitions_to")]
    public required IReadOnlyList<WorkflowStepTransitionToUpsertModel> TransitionsTo { get; init; }

    /// <summary>
    /// Roles allowed to work with items in this step. Defaults to empty — no role restriction.
    /// </summary>
    [JsonPropertyName("role_ids")]
    public IReadOnlyList<Guid> RoleIds { get; init; } = [];
}
