using Kontent.Ai.Management.Models.Types.Elements;

namespace Kontent.Ai.Management.Models.TypeSnippets;

/// <summary>
/// Payload for creating a content type snippet.
/// </summary>
public sealed record ContentTypeSnippetCreateModel
{
    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Elements to add to the snippet. Snippets cannot contain <c>url_slug</c>, <c>subpages</c>, or <c>content_type_snippet</c> elements; including any of these returns 400. Element-level <c>content_group</c> references are also rejected — snippets have no content groups.
    /// </summary>
    [JsonPropertyName("elements")]
    public required IReadOnlyList<ElementMetadataBase> Elements { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Optional.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }
}
