// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("action", "46d20e5c-a72c-5a48-bfae-b054632877ca")]
public sealed partial record Action : IElementsModel
{
    [KontentElement("image", "bee5bc76-a644-546b-8e3b-e3b5c2dfe2c3")]
    public IEnumerable<AssetReference>? Image { get; init; }
    [KontentElement("reference__caption", "75684270-5e43-5d21-b93a-700f85e50853")]
    public string? ReferenceCaption { get; init; }
    [KontentElement("reference__content__item_link", "ed9d88d5-2375-57c3-9916-615eaae7d5da")]
    [AllowedTypes("website_root", "page", "article", "product", "solution")]
    [MaxElements(1)]
    public IEnumerable<Reference>? ReferenceContentItemLink { get; init; }
    [KontentElement("reference__external_uri", "580e3f46-f033-50d4-9f34-4ed91384f4e4")]
    [RegularExpression("^(https?:\\/\\/(?:www\\.|(?!www)))?[a-z0-9]{1,63}([\\-\\.]{1}[a-z0-9]{1,63})*\\.[a-z]{2,63}(:[0-9]{1,5})?(\\/\\S*)?$")]
    public string? ReferenceExternalUri { get; init; }
    [KontentElement("reference__label", "15ee4053-00fd-5d5e-a2d7-4437079251ce")]
    public string? ReferenceLabel { get; init; }
}