// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("article", "5568750a-d7fd-51fa-a8bb-a08940ac5395")]
public sealed partial record Article : IElementsModel
{
    [KontentElement("abstract", "5ae9979f-cc84-5c0b-81d8-65eabf11f2ec")]
    public string? Abstract { get; init; }
    [KontentElement("author", "5be60600-49ac-52f8-a759-ab0ead3a3301")]
    [AllowedTypes("person")]
    [ExactElements(1)]
    public IEnumerable<Reference>? Author { get; init; }
    [KontentElement("content", "7d4b95b0-76fc-552e-8931-c90dd2746399")]
    [AllowedTypes("action", "callout")]
    public RichTextElement? Content { get; init; }
    [KontentElement("hero_image", "ed868ae7-0b90-5752-a53b-aa4cfa2ca56e")]
    [ExactElements(1)]
    public IEnumerable<AssetReference>? HeroImage { get; init; }
    [KontentElement("metadata__description", "e57614c6-e299-51c3-83bc-961f053dfe17")]
    public string? MetadataDescription { get; init; }
    [KontentElement("metadata__keywords", "f46d7c9a-a08f-5987-83e7-a061dd036842")]
    public string? MetadataKeywords { get; init; }
    [KontentElement("metadata__title", "49abab33-e5d1-55bb-9c1b-2f144430da28")]
    public string? MetadataTitle { get; init; }
    [KontentElement("publishing_date", "dba8efd9-052c-557a-9dfd-3f43f966eab8")]
    public DateTimeValue? PublishingDate { get; init; }
    [KontentElement("rating", "9b1f0c3a-2d4e-5f60-8a71-b2c3d4e5f607")]
    public CustomValue? Rating { get; init; }
    [KontentElement("slug", "7b9f3bb2-2efb-5285-8988-bfb66e45cf77")]
    public UrlSlugValue? Slug { get; init; }
    [KontentElement("title", "ae9be828-90fe-5fb4-ae3a-8dfe047e2567")]
    public string? Title { get; init; }
    [KontentElement("type", "c505fded-9c1f-5583-8cf2-dfa4763d2f2a")]
    [AllowedTaxonomyGroup("37f4ed63-efb5-54cb-8cc9-4fdf63223f1e")]
    public IEnumerable<Reference>? Type { get; init; }
}