// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("callout", "72c5b04f-e316-5912-baf2-8ccd2f0ad7a2")]
public sealed partial record Callout : IContentItem
{
    [KontentElement("content", "15a9fc79-e85f-5bb1-8e81-d0362cd93b93")]
    public RichTextElement? Content { get; init; }
    [KontentElement("type", "44dd9032-c950-53b8-91bd-c6c586233311")]
    [MaxElements(1)]
    public IReadOnlyList<CalloutType>? Type { get; init; }
}

public enum CalloutType
{
    [KontentEnumValue("warning", "32fdd712-8627-5782-bbb4-7a4739e9d6ab")]
    Warning,
    [KontentEnumValue("info", "182912d7-d863-5d4a-8a5a-758c4acb2cb7")]
    Info,
    [KontentEnumValue("lightbulb", "e0b420c5-e95f-5a51-83db-39627cecc00b")]
    Lightbulb
}