// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("content_chunk", "aaca014e-ca52-5543-b8fc-76509b245e87")]
public sealed partial record ContentChunk : IElementsModel
{
    [KontentElement("content", "b60790f9-7ed1-5b6d-92ed-15594b9e4253")]
    public RichTextValue? Content { get; init; }
}