// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;
using Kontent.Ai.Management.Models.Types.Elements;

namespace MyProject.Models;

[KontentType("product", "b23ee675-d1f5-53c3-9a8b-a2ed57b10aa6")]
public sealed partial record Product : IElementsModel
{
    [KontentElement("category", "8a5acc99-d4ba-5fa1-9bd0-7a8e86e6e1c9")]
    [AllowedTaxonomyGroup("502de9a1-3673-51e5-bf88-92e76c35cbee")]
    public IReadOnlyList<Reference>? Category { get; init; }
    [KontentElement("metadata__description", "e57614c6-e299-51c3-83bc-961f053dfe17")]
    public string? MetadataDescription { get; init; }
    [KontentElement("metadata__keywords", "f46d7c9a-a08f-5987-83e7-a061dd036842")]
    public string? MetadataKeywords { get; init; }
    [KontentElement("metadata__title", "49abab33-e5d1-55bb-9c1b-2f144430da28")]
    public string? MetadataTitle { get; init; }
    [KontentElement("price", "e80d04c6-7f54-5b7a-b0ec-6c511138ed06")]
    public decimal? Price { get; init; }
    [KontentElement("product_base__description", "30f6b775-071e-5a5a-9394-8251d2081b0e")]
    public string? ProductBaseDescription { get; init; }
    [KontentElement("product_base__main_image", "333cb56d-09c7-58a9-b759-97a0931ce8e6")]
    [AllowedAssetFileTypes(FileType.Adjustable)]
    public IReadOnlyList<AssetReference>? ProductBaseMainImage { get; init; }
    [KontentElement("product_base__name", "9647f1cc-3870-5b67-874b-d56fc2abd7ad")]
    public string? ProductBaseName { get; init; }
    [KontentElement("slug", "ac4fd00c-264e-5189-a4d7-5e7cb7ba1dad")]
    public UrlSlugValue? Slug { get; init; }
}