// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("solution", "f750641e-b3aa-5e4a-9e21-c8871904894d")]
public sealed partial record Solution : IElementsModel
{
    [KontentElement("imaging_technology", "35fc766e-4d5d-58f1-a46f-3ea552eb388d")]
    public IEnumerable<Reference>? ImagingTechnology { get; init; }
    [KontentElement("metadata__description", "e57614c6-e299-51c3-83bc-961f053dfe17")]
    public string? MetadataDescription { get; init; }
    [KontentElement("metadata__keywords", "f46d7c9a-a08f-5987-83e7-a061dd036842")]
    public string? MetadataKeywords { get; init; }
    [KontentElement("metadata__title", "49abab33-e5d1-55bb-9c1b-2f144430da28")]
    public string? MetadataTitle { get; init; }
    [KontentElement("product_base__description", "30f6b775-071e-5a5a-9394-8251d2081b0e")]
    public string? ProductBaseDescription { get; init; }
    [KontentElement("product_base__main_image", "333cb56d-09c7-58a9-b759-97a0931ce8e6")]
    public IEnumerable<AssetReference>? ProductBaseMainImage { get; init; }
    [KontentElement("product_base__name", "9647f1cc-3870-5b67-874b-d56fc2abd7ad")]
    public string? ProductBaseName { get; init; }
    [KontentElement("showcase", "42b24153-7274-550d-8fc1-5f5daea12e89")]
    public RichTextValue? Showcase { get; init; }
    [KontentElement("slug", "0e2c3f0c-9958-53e9-91e4-d6344e08e845")]
    public UrlSlugValue? Slug { get; init; }
}