// <auto-generated>
// This code was generated by Kontent.ai model generator tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To extend this record, create a separate partial record with the same name.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using Kontent.Ai.Management;
using Kontent.Ai.Management.Annotations;
using Kontent.Ai.Management.Models.Content;

namespace MyProject.Models;

[KontentType("website_root", "07acc17d-e2d1-489a-b3cb-d5f6a08eb5ea")]
public sealed partial record WebsiteRoot : IElementsModel
{
    [KontentElement("content", "03fda1d5-fd18-4145-b15f-c8610a40dc33")]
    public IEnumerable<Reference>? Content { get; init; }
    [KontentElement("metadata__description", "e57614c6-e299-51c3-83bc-961f053dfe17")]
    public string? MetadataDescription { get; init; }
    [KontentElement("metadata__keywords", "f46d7c9a-a08f-5987-83e7-a061dd036842")]
    public string? MetadataKeywords { get; init; }
    [KontentElement("metadata__title", "49abab33-e5d1-55bb-9c1b-2f144430da28")]
    public string? MetadataTitle { get; init; }
    [KontentElement("navigation", "49a9000d-8d82-5527-baca-d3fb97bebea0")]
    public IEnumerable<Reference>? Navigation { get; init; }
    [KontentElement("subpages", "f9a9da6a-13a7-4f55-bd1c-68cbfedee157")]
    public IEnumerable<Reference>? Subpages { get; init; }
    [KontentElement("title", "7640bccd-6058-4ae5-a213-5e9811f92178")]
    public string? Title { get; init; }
}