namespace Kontent.Ai.Management.Models.Types;

/// <summary>
/// A logical grouping of elements within a content type. Used as both a request payload (when defining groups on a content type) and a response shape.
/// </summary>
public sealed record ContentGroupModel
{
    /// <summary>
    /// Server-generated content group ID. Present in responses only.
    /// </summary>
    [JsonPropertyName("id")]
    public Guid? Id { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when one was specified on create.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }
}
