namespace Kontent.Ai.Management.Models.TaxonomyGroups;

/// <summary>
/// Shared shape between taxonomy groups and their (recursive) terms. Used as both request payload and response shape.
/// </summary>
public record TaxonomyBaseModel
{
    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when one was specified on create.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }
}
