namespace Kontent.Ai.Management.Models.Content;

/// <summary>
/// Value of a url_slug element on a generated content-type record: the slug plus whether it is custom or
/// server-generated. The envelope converter flattens this to a <c>value</c> + sibling <c>mode</c> on the wire.
/// </summary>
public sealed record UrlSlugValue
{
    /// <summary>The slug. For <see cref="UrlSlugMode.Autogenerated"/> it is server-derived and may be omitted on write.</summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>Whether the slug is custom or auto-generated. Defaults to <see cref="UrlSlugMode.Autogenerated"/>.</summary>
    [JsonPropertyName("mode")]
    public UrlSlugMode Mode { get; init; }

    /// <summary>A bare-string slug is by definition a custom one.</summary>
    public static implicit operator UrlSlugValue(string value) => new() { Value = value, Mode = UrlSlugMode.Custom };
}
