namespace Kontent.Ai.Management.Models.Assets;

/// <summary>
/// Represents a digital asset, such as a document or image.
/// </summary>
public sealed record AssetModel
{
    /// <summary>
    /// Asset ID.
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// Asset codename. Auto-generated by the CMS from the title (or file name) when not supplied on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public required string Codename { get; init; }

    /// <summary>
    /// File name, derived from the underlying binary referenced by <see cref="FileReference"/>.
    /// </summary>
    [JsonPropertyName("file_name")]
    public required string FileName { get; init; }

    /// <summary>
    /// File size in bytes.
    /// </summary>
    [JsonPropertyName("size")]
    public required long Size { get; init; }

    /// <summary>
    /// MIME type, for example "image/jpeg".
    /// </summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>
    /// URL to the asset's binary file.
    /// </summary>
    [JsonPropertyName("url")]
    public required string Url { get; init; }

    /// <summary>
    /// Reference to the binary file backing this asset.
    /// </summary>
    [JsonPropertyName("file_reference")]
    public required FileReference FileReference { get; init; }

    /// <summary>
    /// Per-language alt-text descriptions. Always emitted; individual entries may have <see cref="AssetDescription.Description"/> set to null for languages without a description.
    /// </summary>
    [JsonPropertyName("descriptions")]
    public required IReadOnlyList<AssetDescription> Descriptions { get; init; }

    /// <summary>
    /// Display title. Null when not specified on create.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when one was specified on create.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }

    /// <summary>
    /// ISO-8601 timestamp of the most recent change.
    /// </summary>
    [JsonPropertyName("last_modified")]
    public required DateTime LastModified { get; init; }

    /// <summary>
    /// Image height in pixels. Null when the underlying file is not an image.
    /// </summary>
    [JsonPropertyName("image_height")]
    public int? ImageHeight { get; init; }

    /// <summary>
    /// Image width in pixels. Null when the underlying file is not an image.
    /// </summary>
    [JsonPropertyName("image_width")]
    public int? ImageWidth { get; init; }

    /// <summary>
    /// Containing folder. Null when the asset is at the top level (no folder).
    /// </summary>
    [JsonPropertyName("folder")]
    public AssetFolder? Folder { get; init; }

    /// <summary>
    /// Asset collection assignment. Null on legacy projects without asset-collection support, or when the asset is uncollected.
    /// </summary>
    [JsonPropertyName("collection")]
    public AssetCollectionReference? Collection { get; init; }

    /// <summary>
    /// Taxonomy assignments from the environment's asset type. Always emitted; empty when none are assigned.
    /// </summary>
    [JsonPropertyName("elements")]
    public required IReadOnlyList<AssetElement> Elements { get; init; }
}
