namespace Kontent.Ai.Management.Annotations;

/// <summary>
/// Identifies a generated record as the .NET projection of a Kontent.ai content type. The <see cref="Codename"/>
/// is the type's portable identity and the canonical key used in API write requests. <see cref="Id"/> is the
/// environment-specific identifier; it is what the read path matches against, because MAPI variant responses
/// reference component types by id only. It is optional, but a record without one cannot be resolved as a
/// rich-text component when deserializing a response — typed read therefore requires it.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class KontentTypeAttribute(string codename, string? id = null) : Attribute
{
    /// <summary>Content type codename — the portable identity, stable across environments.</summary>
    public string Codename { get; } = codename ?? throw new ArgumentNullException(nameof(codename));

    /// <summary>
    /// Content type identifier (GUID), or <c>null</c> when not emitted. Environment-specific — stable within an
    /// app-clone lineage, regenerated by API-managed clones. The key the read path resolves rich-text components by.
    /// </summary>
    public string? Id { get; } = id;
}
