using Kontent.Ai.Management.Configuration;
using Kontent.Ai.Management.Models.Content;
using Kontent.Ai.Management.Models.LanguageVariants.Elements;
using Kontent.Ai.Management.Serialization;
using System.Buffers;
using System.Collections;
using System.Text.Json;

namespace Kontent.Ai.Management.Conversion;

/// <summary>
/// Translates between generated content-type records (implementing <see cref="IElementsModel"/>) and the MAPI
/// language-variant <c>elements</c> wire shape — an array of envelopes of the form
/// <c>{ "element": { "codename" | "id": "..." }, "value": &lt;kind-specific&gt;, "components": [...] }</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Write direction</b> emits envelopes keyed by element <em>codename</em> (what MAPI accepts on POST/PUT).
/// Properties whose value is <c>null</c> are skipped — partial-update semantics, matching the migration / scripted-write
/// usage we expect to be the dominant consumer.
/// </para>
/// <para>
/// <b>Read direction</b> matches envelopes by element <em>id</em> first (what MAPI returns), falling back to codename
/// if the response is codename-keyed. Unknown elements in the response are skipped — forward-compat with future MAPI changes.
/// </para>
/// <para>
/// <b>Environment binding.</b> The read path resolves rich-text component types by id (MAPI returns component types by
/// id only — no codename on the wire). Ids are environment-specific: stable within an app-clone lineage, regenerated by
/// API-managed clones. Typed read therefore assumes the generated models carry the ids of the environment being read.
/// Writes stay portable because they key off codenames.
/// </para>
/// <para>
/// Thread-safe; intended to be shared across calls. Reflection cost is paid once per content type
/// (cached in <see cref="ContentItemTypeDescriptor"/>); each (de)serialization allocates only its output buffer plus a
/// list per collection-valued property.
/// </para>
/// </remarks>
internal sealed class ContentItemEnvelopeConverter
{
    private readonly ContentTypeRegistry _registry;
    private readonly JsonSerializerOptions _scalarOptions;

    public ContentItemEnvelopeConverter(ContentTypeRegistry? registry = null, JsonSerializerOptions? scalarOptions = null)
    {
        _registry = registry ?? new ContentTypeRegistry();
        _scalarOptions = scalarOptions ?? RefitSettingsProvider.CreateDefaultJsonSerializerOptions();
    }

    /// <summary>The content-type registry this converter resolves rich-text components through (by type id on read).</summary>
    public ContentTypeRegistry Registry => _registry;

    // ---- Primary API ----

    /// <summary>Writes <paramref name="item"/>'s <c>[KontentElement]</c> properties as a JSON array of envelopes onto <paramref name="writer"/>.</summary>
    public void WriteEnvelopes(Utf8JsonWriter writer, IElementsModel item)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(item);

        var descriptor = ContentItemTypeDescriptor.For(item.GetType());

        writer.WriteStartArray();
        foreach (var prop in descriptor.Properties)
        {
            var value = prop.Property.GetValue(item);
            if (value is null) continue;

            writer.WriteStartObject();
            writer.WritePropertyName("element");
            writer.WriteStartObject();
            writer.WriteString("codename", prop.ElementCodename);
            writer.WriteEndObject();
            WriteValue(writer, prop, value);
            writer.WriteEndObject();
        }
        writer.WriteEndArray();
    }

    /// <summary>Reads a JSON envelopes array into a new instance of <paramref name="contentType"/>.</summary>
    public IElementsModel ReadEnvelopes(JsonElement envelopesArray, Type contentType)
    {
        if (envelopesArray.ValueKind != JsonValueKind.Array)
        {
            throw new ArgumentException($"Expected a JSON array, got {envelopesArray.ValueKind}.", nameof(envelopesArray));
        }
        return ReadEnvelopes(envelopesArray.EnumerateArray(), contentType);
    }

    /// <summary>Reads element envelopes (typically <c>LanguageVariantModel.Elements</c>) into a new instance of <paramref name="contentType"/>.</summary>
    public IElementsModel ReadEnvelopes(IEnumerable<JsonElement> envelopes, Type contentType)
    {
        ArgumentNullException.ThrowIfNull(envelopes);
        ArgumentNullException.ThrowIfNull(contentType);

        // Auto-register the root type itself so it is resolvable by id on recursive descent (a root type can recur as
        // its own rich-text component). Other candidate types (those that may appear as embedded components) are
        // registered by the caller via ContentTypeRegistry.Scan — this primitive stays off the assembly-reflection
        // path and leaves registration scope to the caller.
        _registry.EnsureRegistered(contentType);

        var descriptor = ContentItemTypeDescriptor.For(contentType);
        var instance = (IElementsModel)Activator.CreateInstance(contentType)!;

        foreach (var envelope in envelopes)
        {
            if (!envelope.TryGetProperty("element", out var elementMeta)) continue;

            var prop = ResolveProperty(descriptor, elementMeta);
            if (prop is null) continue;

            if (!envelope.TryGetProperty("value", out var valueElement)) continue;

            try
            {
                var value = ReadValue(valueElement, prop, envelope);
                prop.Property.SetValue(instance, value);
            }
            // Kind-mismatch failures from JsonElement accessors say what was wrong but not where — add the element.
            // The converter's own curated errors (multiple choice, components) already carry it and pass through.
            // STJ's InvalidOperationExceptions are told apart from ours by their exception Source, which starts with
            // the System.Text.Json assembly name; if that marker ever changes, the failure merely surfaces unwrapped.
            catch (Exception ex) when (ex is JsonException or FormatException or KeyNotFoundException
                || (ex is InvalidOperationException && ex.Source?.StartsWith("System.Text.Json", StringComparison.Ordinal) is true))
            {
                throw new InvalidOperationException(
                    $"Failed to read element '{prop.ElementCodename}' on '{contentType.Name}'.", ex);
            }
        }

        return instance;
    }

    // ---- Typed convenience ----

    /// <summary>Writes <paramref name="item"/>'s envelopes and reifies them as the element list an upsert model expects.</summary>
    public IReadOnlyList<BaseElement> ToElements(IElementsModel item)
    {
        ArgumentNullException.ThrowIfNull(item);

        var buffer = new ArrayBufferWriter<byte>();
        using (var writer = new Utf8JsonWriter(buffer))
        {
            WriteEnvelopes(writer, item);
        }
        return JsonSerializer.Deserialize<List<DynamicElement>>(buffer.WrittenSpan, _scalarOptions)!;
    }

    /// <summary>Reads element values (typically a fetched variant's <see cref="DynamicElement"/>s) into a new <typeparamref name="T"/>.</summary>
    public T ReadEnvelopes<T>(IEnumerable<BaseElement> elements) where T : IElementsModel
        => (T)ReadEnvelopes(
            elements.Select(element => JsonSerializer.SerializeToElement(element, element.GetType(), _scalarOptions)),
            typeof(T));

    // ---- Value writers ----

    private void WriteValue(Utf8JsonWriter writer, ContentItemPropertyDescriptor prop, object value)
    {
        switch (prop.Kind)
        {
            case ElementKind.Text:
                writer.WriteString("value", (string)value);
                break;
            case ElementKind.Number:
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, (decimal)value, _scalarOptions);
                break;
            case ElementKind.DateTime:
                var dateTime = (DateTimeValue)value;
                writer.WritePropertyName("value");
                // The API stores a UTC instant (".../Z") with the zone carried separately in display_timezone.
                // UtcDateTime is Kind=Utc, so STJ emits the "Z" form the API returns rather than a numeric offset.
                JsonSerializer.Serialize(writer, dateTime.Value.UtcDateTime, _scalarOptions);
                if (dateTime.DisplayTimeZone is not null) writer.WriteString("display_timezone", dateTime.DisplayTimeZone);
                break;
            case ElementKind.UrlSlug:
                var urlSlug = (UrlSlugValue)value;
                // Omit (don't send null) when the slug is server-derived — matches the "null means omit" contract used
                // for the rest of the envelope. mode is always sent so the server knows autogenerated vs custom.
                if (urlSlug.Value is not null) writer.WriteString("value", urlSlug.Value);
                writer.WritePropertyName("mode");
                JsonSerializer.Serialize(writer, urlSlug.Mode, _scalarOptions);
                break;
            case ElementKind.Custom:
                var custom = (CustomValue)value;
                if (custom.Value is not null) writer.WriteString("value", custom.Value);
                if (custom.SearchableValue is not null) writer.WriteString("searchable_value", custom.SearchableValue);
                break;
            case ElementKind.MultipleChoice:
                WriteMultipleChoice(writer, prop, (IEnumerable)value);
                break;
            case ElementKind.Asset:
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, (IEnumerable<AssetReference>)value, _scalarOptions);
                break;
            case ElementKind.Reference:
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, (IEnumerable<Reference>)value, _scalarOptions);
                break;
            case ElementKind.RichText:
                WriteRichText(writer, (RichTextValue)value);
                break;
            default:
                throw new NotSupportedException($"Unknown element kind: {prop.Kind}");
        }
    }

    private static void WriteMultipleChoice(Utf8JsonWriter writer, ContentItemPropertyDescriptor prop, IEnumerable values)
    {
        var enumDescriptor = EnumDescriptor.For(prop.CollectionElementType!);
        writer.WritePropertyName("value");
        writer.WriteStartArray();
        foreach (var value in values)
        {
            if (!enumDescriptor.CodenameByValue.TryGetValue(value, out var codename))
            {
                throw new InvalidOperationException(
                    $"Enum value '{value}' on '{prop.Property.DeclaringType?.Name}.{prop.Property.Name}' has no [KontentEnumValue] mapping.");
            }
            writer.WriteStartObject();
            writer.WriteString("codename", codename);
            writer.WriteEndObject();
        }
        writer.WriteEndArray();
    }

    private void WriteRichText(Utf8JsonWriter writer, RichTextValue value)
    {
        writer.WriteString("value", value.Value);
        var components = value.Components?.ToList();
        if (components is { Count: > 0 })
        {
            writer.WritePropertyName("components");
            writer.WriteStartArray();
            foreach (var component in components)
            {
                WriteComponent(writer, component);
            }
            writer.WriteEndArray();
        }
    }

    private void WriteComponent(Utf8JsonWriter writer, Component component)
    {
        var descriptor = ContentItemTypeDescriptor.For(component.Content.GetType());

        writer.WriteStartObject();
        writer.WriteString("id", component.Id);
        writer.WritePropertyName("type");
        writer.WriteStartObject();
        writer.WriteString("codename", descriptor.ContentTypeCodename);
        writer.WriteEndObject();
        writer.WritePropertyName("elements");
        WriteEnvelopes(writer, component.Content);
        writer.WriteEndObject();
    }

    // ---- Value readers ----

    private object? ReadValue(JsonElement value, ContentItemPropertyDescriptor prop, JsonElement envelope)
    {
        if (value.ValueKind == JsonValueKind.Null) return null;

        return prop.Kind switch
        {
            ElementKind.Text => value.GetString(),
            ElementKind.Number => value.GetDecimal(),
            ElementKind.DateTime => new DateTimeValue
            {
                Value = value.GetDateTimeOffset(),
                DisplayTimeZone = envelope.TryGetStringProperty("display_timezone", out var tz) ? tz : null,
            },
            ElementKind.UrlSlug => new UrlSlugValue
            {
                Value = value.GetString(),
                Mode = envelope.TryGetProperty("mode", out var mode) && mode.ValueKind == JsonValueKind.String
                    ? mode.Deserialize<UrlSlugMode>(_scalarOptions)
                    : default,
            },
            ElementKind.Custom => new CustomValue
            {
                Value = value.GetString(),
                SearchableValue = envelope.TryGetStringProperty("searchable_value", out var searchable) ? searchable : null,
            },
            ElementKind.MultipleChoice => ReadMultipleChoice(value, prop),
            ElementKind.Asset or ElementKind.Reference => value.Deserialize(prop.Property.PropertyType, _scalarOptions),
            ElementKind.RichText => ReadRichText(value, envelope),
            _ => throw new NotSupportedException($"Unknown element kind: {prop.Kind}"),
        };
    }

    private static object ReadMultipleChoice(JsonElement value, ContentItemPropertyDescriptor prop)
    {
        var enumType = prop.CollectionElementType!;
        var enumDescriptor = EnumDescriptor.For(enumType);
        var listType = typeof(List<>).MakeGenericType(enumType);
        var list = (IList)Activator.CreateInstance(listType)!;

        foreach (var entry in value.EnumerateArray())
        {
            object? member = null;
            if (entry.TryGetStringProperty("id", out var id))
            {
                enumDescriptor.ByItemId.TryGetValue(id, out member);
            }
            if (member is null && entry.TryGetStringProperty("codename", out var codename))
            {
                enumDescriptor.ByCodename.TryGetValue(codename, out member);
            }
            if (member is null)
            {
                // Skipping instead would silently deselect the option on the next upsert of the read model.
                throw new InvalidOperationException(
                    $"Multiple-choice option {entry.GetRawText()} on '{prop.Property.DeclaringType?.Name}.{prop.Property.Name}' " +
                    $"has no matching [KontentEnumValue] member on '{enumType.Name}'. Regenerate the model if the type's options changed.");
            }
            list.Add(member);
        }
        return list;
    }

    private RichTextValue ReadRichText(JsonElement valueElement, JsonElement envelope)
    {
        var html = valueElement.GetString()!;

        List<Component>? components = null;
        if (envelope.TryGetProperty("components", out var componentsArray)
            && componentsArray.ValueKind == JsonValueKind.Array
            && componentsArray.GetArrayLength() > 0)
        {
            components = new List<Component>(componentsArray.GetArrayLength());
            foreach (var componentElem in componentsArray.EnumerateArray())
            {
                components.Add(ReadComponent(componentElem));
            }
        }

        return new RichTextValue { Value = html, Components = components };
    }

    private Component ReadComponent(JsonElement componentElem)
    {
        if (!componentElem.TryGetProperty("id", out var idProp)
            || idProp.ValueKind != JsonValueKind.String
            || !idProp.TryGetGuid(out var id))
        {
            throw new InvalidOperationException(
                "Rich-text component is missing its id. Each component in a Management API response carries a GUID id; " +
                "an entry without one cannot be projected onto a generated record.");
        }

        if (!componentElem.TryGetProperty("type", out var typeRef)
            || !typeRef.TryGetProperty("id", out var typeIdProp)
            || typeIdProp.ValueKind != JsonValueKind.String)
        {
            throw new InvalidOperationException(
                "Rich-text component is missing its content type id. The Management API references component types by id; " +
                "a response without one cannot be projected onto a generated record.");
        }

        var typeId = typeIdProp.GetString()!;
        var contentType = _registry.ResolveById(typeId)
            ?? throw new InvalidOperationException(
                $"Rich-text component references content type id '{typeId}', which is not registered. The model's " +
                "[KontentType] must carry this id, and its assembly must be scanned via ContentTypeRegistry before reading.");

        var elements = componentElem.GetProperty("elements");
        var content = ReadEnvelopes(elements, contentType);

        return new Component { Id = id, Content = content };
    }

    // ---- Internals ----

    private static ContentItemPropertyDescriptor? ResolveProperty(ContentItemTypeDescriptor descriptor, JsonElement elementMeta)
    {
        if (elementMeta.TryGetStringProperty("id", out var id) && descriptor.ByElementId.TryGetValue(id, out var byId))
        {
            return byId;
        }
        if (elementMeta.TryGetStringProperty("codename", out var codename) && descriptor.ByElementCodename.TryGetValue(codename, out var byCodename))
        {
            return byCodename;
        }
        return null;
    }
}
