
namespace Kontent.Ai.Management.Models.Items;

/// <summary>
/// Request payload for creating a new content item via <c>POST /items</c>.
/// </summary>
public sealed record ContentItemCreateModel
{
    /// <summary>
    /// Display name (1-200 chars).
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Codename (1-60 chars). Auto-generated by the CMS from the name when omitted.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Reference to the item's content type.
    /// </summary>
    [JsonPropertyName("type")]
    public required Reference Type { get; init; }

    /// <summary>
    /// Caller-supplied external ID.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }

    /// <summary>
    /// Reference to the collection the item should belong to.
    /// </summary>
    [JsonPropertyName("collection")]
    public Reference? Collection { get; init; }
}
