namespace Kontent.Ai.Management.Models.AssetFolders;

/// <summary>
/// A node in the recursive asset folder hierarchy. Used as both a request payload (when creating or modifying folders) and a response shape.
/// </summary>
public sealed record AssetFolderHierarchy
{
    /// <summary>
    /// Server-generated folder ID. Present in responses only.
    /// The well-known value <c>00000000-0000-0000-0000-000000000000</c> represents assets that sit outside of any folder.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when specified during folder creation or modification.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }

    /// <summary>
    /// Folder codename (1-60 chars). Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Folder name (1-200 chars).
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Nested child folders.
    /// </summary>
    [JsonPropertyName("folders")]
    public IEnumerable<AssetFolderHierarchy>? Folders { get; init; }
}
