using Kontent.Ai.Management.Serialization.Converters;

namespace Kontent.Ai.Management.Models.Types.Elements;

/// <summary>
/// Base shape shared by every element on a content type. Concrete subtypes add the configuration that is specific to each element kind.
/// </summary>
[JsonConverter(typeof(ElementMetadataJsonConverter))]
public abstract record ElementMetadataBase
{
    /// <summary>
    /// Element type discriminator. Each concrete subtype pins its own value.
    /// </summary>
    [JsonPropertyName("type")]
    public abstract ElementMetadataType Type { get; }

    /// <summary>
    /// Server-generated element ID. Present in responses only.
    /// </summary>
    [JsonPropertyName("id")]
    public Guid? Id { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when one was specified on create.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }

    /// <summary>
    /// Reference to the content group this element belongs to. Required on create only when the content type defines content groups.
    /// </summary>
    [JsonPropertyName("content_group")]
    public Reference? ContentGroup { get; init; }
}
