namespace Kontent.Ai.Management.Models.Types.Elements;

/// <summary>
/// A single option on a multiple-choice element. Used as both a request payload and a response shape.
/// </summary>
public sealed record MultipleChoiceOptionModel
{
    /// <summary>
    /// Server-generated option ID. Present in responses only.
    /// </summary>
    [JsonPropertyName("id")]
    public Guid? Id { get; init; }

    /// <summary>
    /// Codename. Auto-generated by the CMS when omitted on create.
    /// </summary>
    [JsonPropertyName("codename")]
    public string? Codename { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Caller-supplied external ID. Only present when one was specified on create.
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }
}
