using Kontent.Ai.Management.Models.Content;

namespace Kontent.Ai.Management.Models.LanguageVariants.Elements;

/// <summary>Value of a url_slug element: the slug plus whether it is custom or auto-generated.</summary>
/// <remarks>Use this to set a url_slug element by hand in the untyped element array; <c>Element</c> says which element it targets. With a generated content-type record, set the element via <see cref="Content.UrlSlugValue"/> instead.</remarks>
public sealed record UrlSlugElement : BaseElement
{
    /// <summary>The slug. For <see cref="UrlSlugMode.Autogenerated"/> the server derives it and this may be omitted.</summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>Whether the slug is custom or auto-generated.</summary>
    [JsonPropertyName("mode")]
    public UrlSlugMode Mode { get; init; }
}
