using System.Text.Json.Serialization;
using Kontent.Ai.Management.Models.Content;

namespace Kontent.Ai.Management.Models.LanguageVariants.Elements;

/// <summary>Value of a url_slug element: the slug plus whether it is custom or auto-generated.</summary>
public sealed record UrlSlugElement : BaseElement
{
    /// <summary>The slug. For <see cref="UrlSlugMode.Autogenerated"/> the server derives it and this may be omitted.</summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>Whether the slug is custom or auto-generated.</summary>
    [JsonPropertyName("mode")]
    public UrlSlugMode Mode { get; init; }
}
